# default arguments yml
pagesize:
  - 896
  - 896
marginLeft: 20
marginRight: 20
marginTop: 20
marginBottom: 20
forceOnePage: false
autoAdjustHeight: false
savePDF: false
saveImage: false
dpi: 96
overwrite: false
save_format: "jpeg"
css: "p {font-size: 9px;}"
css_path: null
