# default arguments yml
pagesize:
  - 896
  - 896
marginLeft: 0
marginRight: 0
marginTop: 0
marginBottom: 0
forceOnePage: false
autoAdjustHeight: false
savePDF: false
saveImage: false
dpi: 96
overwrite: false
save_format: "jpeg"
save_kwargs:
  quality: 50
  optimize: true
  subsampling: 2
css: null
css_path: config/css/locomo.css
