# default arguments yml
pagesize:
  - 1792
  - 1792
marginLeft: 0
marginRight: 0
marginTop: 0
marginBottom: 0
forceOnePage: false
autoAdjustHeight: false
savePDF: false
saveImage: false
dpi: 96
overwrite: false
save_format: "jpeg"
save_kwargs:
  quality: 60
  optimize: true
  subsampling: 2
css: "p {font-size: 12px;} span {background-color: lightgray;} span:nth-child(even) {background-color: lightgreen;}"
css_path: null
